version: '3'
services:
  mysql:
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: phoneApp
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./bbdd/bbdd.sql:/docker-entrypoint-initdb.d/bbdd.sql
  phones:
    command: npm run start:dev
    volumes:
      - ./phones:/usr/src/app/phones
      - ./phones/package.json:/usr/src/app/phones/package.json
      - ./phones/server.js:/usr/src/app/phones/server.js
    depends_on:
      - mysql
  orders:
    command: npm run start:dev
    volumes:
      - ./orders:/usr/src/app/orders
      - ./orders/package.json:/usr/src/app/orders/package.json
      - ./orders/server.js:/usr/src/app/orders/server.js
    depends_on:
      - mysql