version: '3'
services:
  mysql:
    image: mysql:5.7
  phones:
    build:
      context: ./phones
      dockerfile: Dockerfile
    env_file:
      - ./phones/.env
    ports:
      - "8080:3000"
  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    env_file:
      - ./orders/.env
    ports:
      - "8081:3001"