version: '3'
services:
  mysql:
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: phoneApp
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./bbdd/bbdd.sql:/docker-entrypoint-initdb.d/bbdd.sql
  app:
    command: npm run start:dev
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mysql