#%RAML 1.0 Library

types: 
  Phone:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: number
      image:
        type: string
        required: false