#%RAML 1.0
title: Kuestions2 API
version: 0.0.1
description: !include docs/apiDescription.md

resourceTypes: 
  collection: !include resourceTypes/collection.raml

uses:
  Phones: types/phones.raml
  Order: types/order.raml

/phones:
  description: Service for managing phones.
  type: collection
  get:
    description: Resource for retrieving the phones list.
    responses: 
      200:
        body: 
          application/json:
            example: !include examples/phones/get_200.json
            type: object
            properties: 
              data:
                type: Phones.Phones

/orders:
  description: Service for managing orders.
  post:
    description: Resource for creating a new order.
    body:
      application/json:
        example: !include examples/orders/post_request.json
        type: Order.OrderBody
    responses: 
      201:
        body: 
          application/json:
            example: !include examples/orders/post_201.json
            type: object
            properties: 
              data:
                type: Order.OrderResponse